name: Update China IP Allocations

on:
  schedule:
    - cron: "0 19 * * *"   # This is 3:00 AM Beijing time (UTC+8)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub

    - name: Run update script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python update_cn_ip.py
